### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by Cadene** [itaicaspi/inception-v4.torch#1]
Hi there,

First of all, thank you for your implementation of inception-v4 on torch :+1: 
I'm looking for a pretrained inception-v4 on ILSVRC2015 or earlier.
Where could I find such a thing ?

Thanks

**Comment by mastrcheif** [comment]
I am also curious to know that

**Comment by itaicaspi** [comment]
Thanks for the comments guys.
I am sorry but I am not aware of any pretrained model for inception-v4.

**Comment by Cadene** [comment]
I got some information about an upcoming release by the inception-v4 / inception-resnet authors.
It might be for this coming week.
